{{- range .Values.backends }}
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: {{ .name }}-backend
spec:
  mcp:
    targets:
      - name: {{ .name }}
        static:
          host: {{ .host }}
          port: {{ .port }}
          {{- if .path }}
          path: {{ .path }}
          {{- end }}
          protocol: {{ .protocol }}
{{- if .tls }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .name }}-tls
spec:
  targetRefs:
    - name: {{ .name }}-backend
      kind: AgentgatewayBackend
      group: agentgateway.dev
      sectionName: {{ .name }}
  validation:
    hostname: {{ .tls.hostname }}
    wellKnownCACertificates: {{ .tls.wellKnownCACertificates }}
{{- end }}
{{- end }}
