apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    {{- range .Values.listeners }}
    - name: {{ .name | trunc 15 }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}
    {{- if and .Values.admin .Values.admin.enabled }}
    - name: admin
      port: 15000
      targetPort: {{ .Values.admin.sidecar.port }}
      protocol: TCP
    {{- end }}