apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.configmap.namespace }}
data:
  config.yaml: |
    binds:
      - port: 3000
        listeners:
          - routes:
              - policies:
                  cors:
                    allowOrigins:
                      {{- range .Values.configmap.cors.allowOrigins }}
                      - {{ . | quote }}
                      {{- end }}
                    allowHeaders:
                      {{- range .Values.configmap.cors.allowHeaders }}
                      - {{ . | quote }}
                      {{- end }}
                    exposeHeaders:
                      {{- range .Values.configmap.cors.exposeHeaders }}
                      - {{ . | quote }}
                      {{- end }}
                backends:
                  - mcp:
                      targets:
                        {{- range .Values.configmap.mcpBackends }}
                        - name: {{ .name }}
                          mcp:
                            host: https://{{ .host }}{{ .path }}
                          policies:
                            backendTLS:
                              insecure: {{ if .tls }}true{{ else }}false{{ end }}
                        {{- end }}
