configmap:
  cors:
    allowOrigins:
      - "http://localhost:3080"
  mcpBackends:
    - name: ms365-teams
      host: m365.kindcoast-e367d61d.switzerlandnorth.azurecontainerapps.io
      port: 443
      path: /mcp
      protocol: StreamableHTTP
      tls:
        insecureSkipVerify: All
    - name: ms365-dev
      host: ms365-mcp-dev.kindredgroup.com
      port: 443
      path: /mcp
      protocol: StreamableHTTP
      tls:
        insecureSkipVerify: All


deployment:
  replicas: 1
  resources: {}
